#pragma once

#include <array>
#include <string_view>

enum class AddrMode {
  Illegal,
  Implied,
  IndX,
  ZeroPage,
  Immediate,
  Absolute,
};

struct InstItem {
  std::string_view name;
  AddrMode         mode;
  size_t           size;

  consteval InstItem(): name("ILLEGAL"), mode(AddrMode::Illegal), size(1) {}

  consteval InstItem(std::string_view n, AddrMode a, size_t s): name(n), mode(a), size(s) {}
};

constexpr std::array<InstItem, 256> CPU_INSTS = {
    InstItem("BRK", AddrMode::Implied, 1),
    InstItem("ORA", AddrMode::IndX, 2),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem("ORA", AddrMode::ZeroPage, 2),
    InstItem("ASL", AddrMode::ZeroPage, 2),
    InstItem(),
    InstItem("PHP", AddrMode::Implied, 1),
    InstItem("ORA", AddrMode::Immediate, 2),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem("SEI", AddrMode::Implied, 1),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem("TSX", AddrMode::Implied, 1),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem("STX", AddrMode::Absolute, 3),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem("LDX", AddrMode::Immediate, 2),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem("CLD", AddrMode::Implied, 1),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
    InstItem(),
};
